development:
  secret_key_base: f4a7ab09eee051a2678163291fdd48f4231abd8eb72a6b3733aec2a57cc4faec6733fc76897db095543398e076e24824cf316834bea2d657f547ad5b40028ceb
  
  database_name_development: Delivery_Provider_API_development
  database_name_production: Delivery_Provider_API_production
  database_name_test: Delivery_Provider_API_test
  firebase_API_key: AAAASIV9WLc:APA91bGI29Y5lSrSBDXSZ8FNqqFEZhjZKtafK2Mccp_muwCD7lD9LKvz8INKPgX75NhMNL-2nPUbm6nyHhgyA-EKiU6zHfXq4I-mf_-GQ5xr6WScw6kTtBXDFQEhl6tAoP1cVKfco1fy

  database_user: root
  database_password: Minos1994

  base_url: https://driveo.herokuapp.com
# production credentials
production:
    secret_key_base: f4a7ab09eee051a2678163291fdd48f4231abd8eb72a6b3733aec2a57cc4faec6733fc76897db095543398e076e24824cf316834bea2d657f547ad5b40028ceb
    firebase_API_key: AAAASIV9WLc:APA91bGI29Y5lSrSBDXSZ8FNqqFEZhjZKtafK2Mccp_muwCD7lD9LKvz8INKPgX75NhMNL-2nPUbm6nyHhgyA-EKiU6zHfXq4I-mf_-GQ5xr6WScw6kTtBXDFQEhl6tAoP1cVKfco1fy
    base_url: https://driveo.herokuapp.com